### ISSUE TITLE
Can't open laptop

### ISSUE THREAD

**Issue by JCionx** [omnixerio/devices-mod#115]
**Describe the bug**
Cannot open laptops in game on 1.20.1

**To Reproduce**
1. Grab a laptop
2. Try to open it
3. Realize you can't

**Expected behavior**
Expected the laptop to open

**Please complete the following information:**
 - OS: macOS
 - Minecraft version: 1.20.1
 - Devices Mod Version: 0.8.2
 - Architectury API Version: 9.2.14

**FOR FORGE:**
 - Forge version: 47.3.0

**Comment by QboiDev** [comment]
Have you tried to shift right click?
Also which macOS version?

**Comment by JCionx** [comment]
I tried shift right click.
I'm using macOS 15.

**Comment by JCionx** [comment]
I just noticed that I was using a mod that makes the player carry blocks when shift+right clicking. The laptops work fine without that mod.
