### ISSUE TITLE
curseforge and 1.19.2 port?

### ISSUE THREAD

**Issue by lostopkk** [omnixerio/devices-mod#20]
just a question.

**Comment by QboiDev** [comment]
We're going to do 1.18.2 first until the mod is stable enough.
And about CurseForge, it's here: https://www.curseforge.com/minecraft/mc-mods/devices-mod
I couldn't use the name ‘‘Devices Mod’’ because CurseForge didn't like that I used the word ‘‘mod’’ in the name.
