### ISSUE TITLE
Game does not load

### ISSUE THREAD

**Issue by Ch1216** [omnixerio/devices-mod#21]
Here is a crash report
[crash-2022-08-22_15.26.22-fml.txt](https://github.com/Ultreon/devices-mod/files/9397055/crash-2022-08-22_15.26.22-fml.txt)

And here is a log
[latest.log](https://github.com/Ultreon/devices-mod/files/9397058/latest.log)

**Comment by QboiDev** [comment]
Huh, tested it.
UltranLang seems to be broken. ~~@Jab125 can you try to fix that?~~ Nvm seems to work, but probably is an older version of forge being used.

**Comment by Ch1216** [comment]
what version forge and mod with any dependency and its versions do i use to play the mod

**Comment by QboiDev** [comment]
I tested it on Fabric with loader `0.14.9`, and Fabric API `0.58.0`
For Forge I tested it on `40.1.74`.

Other info:
Minecraft version: `1.18.2`
Mod version: `0.5.0+64`
It requires [Architectury API](https://modrinth.com/mod/architectury-api)
*And yes, it supports both Forge and Fabric.*

**Comment by QboiDev** [comment]
You probably need to use a newer version of Forge, I used `40.1.74` and it should work.

**Comment by Jab125** [comment]
Forge 40.1.14 is outdated, only the most recent builds of forge have the Jar in Jar functionality

**Comment by Ch1216** [comment]
dependencys should probs say it requires forge 40.1.60 then also add the architectury api requirement
