### ISSUE TITLE
printer crash

### ISSUE THREAD

**Issue by ImDolphin4878** [omnixerio/devices-mod#24]
when i try to place the printer, minecraft crash

**Comment by QboiDev** [comment]
We need a crash report or log to find out what caused the crash.
Report is in `.minecraft/crash-reports` and log is in `.minecraft/logs`.

**Comment by Jab125** [comment]
Fixed in https://github.com/Ultreon/devices-mod/commit/ae81e538b3eb76d5b30105e47c69c25be0e11dd8, reopen if not fixed.
