### ISSUE TITLE
my game enters, when I go to create the world it gives all these errors my game is 100% cpu and I can't play

### ISSUE THREAD

**Issue by lostopkk** [omnixerio/devices-mod#27]
**To Reproduce**
1. Go to 'Minecraft'
2. Click on 'Singleplayer'
4. Game crashed

**Logs**
https://mclo.gs/PDx7KHK

**Crash report**
Add a crash report to the issue, this is essential for developers to know what went wrong.

**Please complete the following information:**
 - OS: [e.g. Windows]
 - Minecraft version 1.19.2
 - Devices Mod Version: 0.5.0+80
 - Architectury API Version: 6.2.43

**FOR FABRIC:**
 - Fabric Loader version 0.14.6
 - Fabric API version 0.60.0

**Additional context**

**Additional mods used**
Optionally, give a list of mods used (as long it isn't many).

**Comment by QboiDev** [comment]
@Jab125 what tf did you do to even cause this, you did the 1.19.2 port.
Recipes need to be valid for Minecraft worlds to load lol.

**Comment by lostopkk** [comment]
> @Jab125 what tf did you do to even cause this, you did the 1.19.2 port. Recipes need to be valid for Minecraft worlds to load lol.

It takes a long time and I can't play literally, when I open the world I think it's going to go longer, like 1 hour

**Comment by QboiDev** [comment]
It could be because of a slow computer, but the cause of being slower is that a **lot** of recipes are invalid.

**Comment by lostopkk** [comment]
any tips to help with this? apparently it's not just in your mod

**Comment by QboiDev** [comment]
I guess if you have a better computer laying around it may work, otherwise you could wait until we fix all the errors happening with the recipes. Because those are the cause of Minecraft slowing down I guess.

**Comment by lostopkk** [comment]
but why cause these errors? is this something natural to minecraft? why does it usually not take that long when i do this

**Comment by QboiDev** [comment]
I think we have overlooked those errors when porting the mod from 1.12.2 and/or 1.18.2.
My guess is that it's because of @Jab125 porting the office chair. The recipes for that are broken it seems.

**Comment by lostopkk** [comment]
> I think we have overlooked those errors when porting the mod from 1.12.2 and/or 1.18.2. My guess is that it's because of @Jab125 porting the office chair. The recipes for that are broken it seems.

this log only appears yours, but when i test other famous mods it also gives the same error, i just don't know what to do lol

**Comment by lostopkk** [comment]
https://mclo.gs/HpL6PGz
latest log without devices mod

**Comment by QboiDev** [comment]
> https://mclo.gs/HpL6PGz latest log without devices mod

Seems like a mod with the id `fireworkfrenzy` has invalid recipes.
I think this mod is maybe causing it this time.

**Comment by lostopkk** [comment]
> > https://mclo.gs/HpL6PGz latest log without devices mod
> 
> Seems like a mod with the id `fireworkfrenzy` has invalid recipes. I think this mod is maybe causing it this time.

In that case, will there be any solution on your part? I love this mod ported to fabric and really wanted to use it

**Comment by QboiDev** [comment]
I'm not sure which mod exactly is causing it, but the only way of testing it is using a profiler, but that's a tool made for developers. I guess an option is to try to enable/disable mods.

**Comment by lostopkk** [comment]
like a spark?

**Comment by QboiDev** [comment]
it could maybe be used, but therefore it needs to not hard-crash, so you need to let it load the world fully to get the information for the profiling needed.

**Comment by QboiDev** [comment]
External tools are more recommended.

**Comment by lostopkk** [comment]
> External tools are more recommended.

type which?

**Comment by QboiDev** [comment]
Programs/apps like JProfiler, I think I need to find out myself, or @Jab125 (yes 3rd ping).

**Comment by QboiDev** [comment]
Can I get a list of mods used? (Versions included)

**Comment by lostopkk** [comment]
> Can I get a list of mods used? (Versions included)

there are many mods, let me make the Jprofiler without problems and send the log

**Comment by QboiDev** [comment]
Can you somehow create a curseforge modpack from it?

**Comment by lostopkk** [comment]
> Can you somehow create a curseforge modpack from it?

is a private modpack for friends, wanting to build something

**Comment by lostopkk** [comment]
https://drive.google.com/file/d/1ljjzaXtDd0gxw1zEfTwVOATRXES-_8in/view?usp=sharing
does this help in any way? @Qboi123

**Comment by lostopkk** [comment]
@Qboi123 I managed to solve both the delay and I opened normal minecraft, some of these mods are in conflict for some reason and I don't know what it is, I just know that I took them out and solved my problem, thank you very much for the support

architect's palette, better third person, bigbuckets, catwalks, chat heads, chimes, connectivity, fireworkfrenzy, go fish, jello, letmedespawn, magitekmechs, modern dynamics, modern elevators, morebannerlayers, MTR, overweightfarm, plushie, rocks, scout, sprintometers, the printer, wired redstone, wenospeakumbrellarino
