### ISSUE TITLE
Error when opening on fabric dedicated server

### ISSUE THREAD

**Issue by lostopkk** [omnixerio/devices-mod#28]
**Describe the bug**
Error when starting a dedicated server

**Please complete the following information:**
 - OS: Windows
 - Minecraft version: 1.19.2
 - Devices Mod Version: 0.5.0 build 80
 - Architectury API Version: 6.2.43

**FOR FABRIC:**
 - Fabric Loader version 0.14.6
 - Fabric API version 0.60.0

**Log**
https://mclo.gs/nbgaATV

**Comment by QboiDev** [comment]
@Jab125 have you fixed this already?

**Comment by Jab125** [comment]
> @Jab125 have you fixed this already?

Yesn't

**Comment by QboiDev** [comment]
> Yesn't

Brūh

**Comment by Jab125** [comment]
Fixed in 349661135ffef9944abcd345baf0eb80b2755f1f
