### ISSUE TITLE
[CRASH] MissingField: Error reading fabric.mod.json file for mod

### ISSUE THREAD

**Issue by spjoes** [omnixerio/devices-mod#31]
MissingField: Error reading fabric.mod.json file for mod at: 
C:\Users\USERNAME\AppData\Roaming\.minecraft\mods\devices-0.5.1-127.jar (also tried with devices-0.5.1-121)
Missing required field "version".

**Comment by spjoes** [comment]
Forge works fine

**Comment by Jab125** [comment]
Use the issue template and post a crash log

**Comment by QboiDev** [comment]
> Use the issue template and post a crash log

I think the message itself is clear enough tho.
Still it's indeed meant to use the issue template and share a crash report or log.

**Comment by spjoes** [comment]
There is no template anywhere I can see?

**Comment by QboiDev** [comment]
@Jab125 bruh where did the templates go?

**Comment by QboiDev** [comment]
Templates should show now since #32 
Just create a new issue and select an option.
