### ISSUE TITLE
Apps are wiped after exiting the laptop menu

### ISSUE THREAD

**Issue by venomboss985** [omnixerio/devices-mod#43]
**Describe the bug**
When installing an app on the laptop, the app functions as normal. However, after exiting and going back into the laptop, all of the installed apps disappear and need to be reinstalled.

**To Reproduce**
1. Open laptop
2. Install any app (it does not matter if the app gets ran or not)
3. Exit the laptop
4. Open the laptop again and look at the taskbar

**Expected behavior**
Taskbar should be populated with installed apps

**Screenshots**
[Short video of issue](https://user-images.githubusercontent.com/45863773/200129484-131247a1-9238-434d-87d0-ee7c0a6e6bd4.mp4)

**Please complete the following information:**
 - OS: Windows 10 22H2
 - Minecraft version: 1.19.2
 - Devices Mod Version: 0.5.4-157
 - Architectury API Version: 6.3.49

**FOR FORGE:**
 - Forge version: 43.1.47

**Additional context**
Files and personalization seems to be persistent after exiting (ex. Created notes can still be found in the filesystem and UI/background changes will remain unchanged)

**Comment by QboiDev** [comment]
Yeah, I noticed that too, it might be a saving issue.
I'm currently busy with some other projects for someone else, so I let @Jab125 do it this time.

**Comment by Jab125** [comment]
💀 will work on

**Comment by Jab125** [comment]
will fix after a refactor is completed
