### ISSUE TITLE
Battery Percentage in GUI of REAL battery if present.

### ISSUE THREAD

**Issue by QboiDev** [omnixerio/devices-mod#46]
**Is your feature request related to a problem? Please describe.**
Not in this case.

**Describe the solution you'd like**
Having the battery percentage of the REAL computer inside the laptop ingame.

**Describe alternatives you've considered (optional, but recommended)**
Alternatives are faking the battery percentage. (Which is lame imo)

**Additional context**
Mod where I have managed to do it: [Ultreon/mc-battery-info](https://github.com/Ultreon/mc-battery-info)

**Comment by Jab125** [comment]
I was thinking about giving laptops actual battery instead of your IRL battery
(there's a wip system that displays the laptop screen for everyone and this wouldn't work

**Comment by QboiDev** [comment]
> (there's a wip system that displays the laptop screen for everyone and this wouldn't work

Understandable.
