### ISSUE TITLE
GitWeb App is not contacting the api to grab the sites

### ISSUE THREAD

**Issue by wildmaster84** [omnixerio/devices-mod#47]
**Describe the bug**
The GitWeb app is not getting the raw url from github. When editing the index on github, the app will not register the changes even after a reboot.

**Please complete the following information:**
 - OS: [e.g. Windows]
 - Minecraft version 1.19.2 Forge
 - Devices Mod Version: [example: 0.5.4-local
 - Architectury API Version: [example: 6.3.56

**FOR FORGE:**
 - Forge version 43.1.65

**Comment by Jab125** [comment]
explain with a video recording

**Comment by wildmaster84** [comment]
heres the video (https://youtu.be/f0zs0x1LnpU)

**Comment by wildmaster84** [comment]
Issue was misconfigured register file
