### ISSUE TITLE
Broken Textures And Models

### ISSUE THREAD

**Issue by wildmaster84** [omnixerio/devices-mod#48]
**Describe the bug**
The textures for flash drives, printers and routers are broken perhaps due to how the way the mod changes its color.
While creating a workaround, printers and flash drives do not work at all with no errors being logged via server or client.

**Expected behavior**
Working printer and flash drive with textures

**Screenshots**
![2022-12-08_16 50 29](https://user-images.githubusercontent.com/46942741/206575730-8d450e81-16b0-4d7c-b66f-d6df6244e5dd.png)
![2022-12-08_16 50 23](https://user-images.githubusercontent.com/46942741/206575783-174e2893-73ea-4f1a-aaba-082ed0857984.png)

**Please complete the following information:**
 - OS: Windows 10 + Windows 11
 - Minecraft version 1.19.2
 - Devices Mod Version: 0.5.4
 - Architectury API Version: 6.3.56

**FOR FORGE:**
 - Forge version 43.1.65

**Comment by QboiDev** [comment]
I'm unsure when this was fixed, but it seems to be working in Devices Mod 0.7.4 and 0.8.1.
(Also, support for 1.19.2 was dropped a while back, but maybe, just maybe I will backport it)
