### ISSUE TITLE
Issue with app metadata resource (still happening).

### ISSUE THREAD

**Issue by QboiDev** [omnixerio/devices-mod#50]
**To Reproduce**
1. Use [Ultreon/devices-mod-template](https://github.com/Ultreon/devices-mod-template/tree/forge)
2. Sync the project.
3. Generate runs with `gradle genIntellijRuns`
4. Run the `runClient` configuration.

**Logs**
[debug.log](https://github.com/Ultreon/devices-mod/files/10212694/debug.log)

**Crash report**
[crash-2022-12-13_00.06.16-fml.txt](https://github.com/Ultreon/devices-mod/files/10212695/crash-2022-12-13_00.06.16-fml.txt)

**Please complete the following information:**
 - OS: **Windows 11**
 - Minecraft version **1.19.2**
 - Devices Mod Version: **0.5.5**
 - Architectury API Version: **6.2.43**

**FOR FORGE:**
 - Forge version **43.2.0**

**Additional context**
 * It's ran in the Development Environment using `runClient`.

**Additional mods used**
`N/A`

*P.S. It's possible that the same happens on fabric.*

**Comment by Jab125** [comment]
You need to subscribe to `ForgeApplicationRegistration` setup mods.toml to initialise earlier than the main devices mod

**Comment by Jab125** [comment]
Same for fabric, you need to use the dedicated entrypoints

**Comment by Jab125** [comment]
Look at the `fabric-testmod` module to see how it's done in fabric
