### ISSUE TITLE
Laptop won't drop on breaking it

### ISSUE THREAD

**Issue by Numerosityy** [omnixerio/devices-mod#71]
**Describe the bug**
When using any tool, laptops won't drop.

**To Reproduce**
Self explanatory

**Expected behavior**
The laptop should drop

**Please complete the following information:**
 - Windows
 - 1.19.2
 - 0.7.2
 - Occurs on any version of Architectury

**FOR FORGE:**
 - Occurs on any version of Forge

**Comment by QboiDev** [comment]
Are you able to test if this version works for you in a test world: [`devices-0.7.2.jar at CircleCI`](https://output.circle-artifacts.com/output/job/d3bc0a97-0bc3-4629-aa75-00c82707a38a/artifacts/0/build/libs/merged/devices-0.7.2.jar)
(this is the one based on the code at https://github.com/Ultreon/devices-mod/commit/21dde8e625aaefbafc174a1f4fac9f255c26fa0a)

**Comment by Numerosityy** [comment]
Can confirm, this works now. Ofc, would be nice to have this fix on other versions than just 1.19.3
