### ISSUE TITLE
Flash Drive file structure is corrupt after obtaining

### ISSUE THREAD

**Issue by QboiDev** [omnixerio/devices-mod#80]
**Describe the bug**
When using the flash drive, the file browser is unable to retrieve the drive structure for the flash drive.
The error message states `Unable to retrieve drive structure for 'XXXX'` where `XXXX` is the name of that flash drive.

```
[Netty Server IO #1/INFO] (Devices : Debugger) pos == -6, 76, 5
[Netty Server IO #1/INFO] (Devices : Debugger) block->registryName == devices:white_laptop
[Netty Server IO #1/INFO] (Devices : Debugger) level->isClient == false
[Netty Server IO #1/INFO] (Devices : Debugger) tileEntity == null
```

**To Reproduce**
1. Get a Flash Drive of any color (in game)
2. Get a Laptop of any color (in game)
3. Put that flash drive in the laptop.
4. Open the laptop.
5. Go to the File Browser app.
6. In the disk selection select the flash drive.
7. See error on dialog. And the game's log files for info.

**Expected behavior**
The file browser should be able to retrieve the structure and show the contents of the flash drive.

**Screenshots**
![image](https://github.com/Ultreon/devices-mod/assets/30625109/c398173b-6b49-4db6-a87d-06c6e9f73166)

**Please complete the following information:**
 - OS: `Windows 11 Pro 22H2 (OS version 22621.2134)`
 - Minecraft version `1.19.3, 1.20.1`
 - Devices Mod Version: `0.7.3, 0.8.0`
 - Architectury API Version: `7.1.70`

**FOR FABRIC:**
 - Fabric Loader version `0.14.14`
 - Fabric API version `0.7.2+1.19.3`

**Additional context**
This issue seems to also happen on Devices Mod 0.7.3 for 1.19.3.

**Comment by XyperCode** [comment]
Does this still happen in version 0.8.2?

**Comment by QboiDev** [comment]
Should be fixed in https://github.com/Ultreon/devices-mod/commit/8082aacebe76651059991347d31d2ac14daca927
