### ISSUE TITLE
I can't load my server with this mod

### ISSUE THREAD

**Issue by PonCorp** [omnixerio/devices-mod#84]
**following information:**
 - OS: Linux arch amd64 version 5.15.0-78-generic
 - Minecraft version: 1.19.3
 - Devices Mod Version: 0.7.2
 - Architectury API Version: 7.1.86

**FORGE:**
 - Forge version 44.1.23

**Additional context**
My server gives a error on start

**Additional mods used**
geckolib
Public Transport
architectury
Devices Mod

Log is here
[crash-2023-11-23_09.1858-fml.txt](https://github.com/Ultreon/devices-mod/files/13447462/crash-2023-11-23_09.1858-fml.txt)

**Comment by QboiDev** [comment]
Wait wut, seems like the mod tries to load client-side classes *again*.

**Comment by QboiDev** [comment]
Should be fixed in 0.7.4 (now releasing)
If you still encounter the same issue with the new version let me know.
