### ISSUE TITLE
game crashes trying to load game to main menu

### ISSUE THREAD

**Issue by Tsumiki129** [omnixerio/devices-mod#98]
hi with the mod in are mod pack the game is crashing for me wen starting the game as it goes to load main menu it just crashes out here is the log for it.

[crash-2024-02-25_16.11.36-client.txt](https://github.com/Ultreon/devices-mod/files/14397040/crash-2024-02-25_16.11.36-client.txt)

**Comment by QboiDev** [comment]
Mod configuration file got corrupted/damaged.
I guess just reset the config file.
(Can be done by deleting the config file and letting it create a new one)

File: `devices-client.toml`

**Comment by QboiDev** [comment]
Closing this as there hasn't been a response in 3 weeks.
